# Generated by Django 4.0 on 2023-06-19 07:56

import Inventory.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('الامريكية', 'الامريكية'), ('رياض اطفال', 'رياض اطفال'), ('تمهيدى', 'تمهيدى'), ('ابتدائى ابو بكر', 'ابتدائى ابو بكر'), ('ابتدائى معاذ', 'ابتدائى معاذ'), ('اعدادى', 'اعدادى'), ('الادارة', 'الادارة')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='download.png', upload_to='photo')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.building')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.building')),
            ],
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('barcode_number', models.SlugField(blank=True, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('Building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.building')),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product_category')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Outgoing', to='Inventory.brand')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.responsibleperson')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.room')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_incoming', models.BooleanField(default=True)),
                ('is_outgoing', models.BooleanField(default=False)),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_invoice', models.ImageField(upload_to='purchase_invoices/')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomings', to='Inventory.brand')),
                ('product_category', models.ManyToManyField(related_name='incomings', to='Inventory.Product_Category')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='Inventory.product_category'),
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_number', models.FileField(upload_to=Inventory.models.get_barcode_path)),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.incoming')),
            ],
        ),
    ]
