# Generated by Django 4.0 on 2023-06-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoing',
            old_name='Building',
            new_name='building',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='Product_Category',
        ),
        migrations.AddField(
            model_name='outgoing',
            name='product_category',
            field=models.ManyToManyField(related_name='outgoing', to='Inventory.Product_Category'),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='Inventory.brand'),
        ),
    ]
