# Generated by Django 4.0 on 2023-06-26 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringscreen',
            name='is_incoming',
        ),
        migrations.RemoveField(
            model_name='monitoringscreen',
            name='is_outgoing',
        ),
        migrations.AddField(
            model_name='monitoringscreen',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventory.building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoringscreen',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventory.room'),
            preserve_default=False,
        ),
    ]
