# Generated by Django 4.0 on 2023-06-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Inventory.building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='floor_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
