# Generated by Django 4.0 on 2023-06-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_remove_room_building_alter_building_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoing',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
