# Generated by Django 4.0 on 2023-06-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_outgoing_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoing',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
